import { UMLClass, UMLRelationship } from '../types/uml';

export interface DiagramTemplate {
  id: string;
  name: string;
  description: string;
  classes: UMLClass[];
  relationships: UMLRelationship[];
}

export const TEMPLATES: DiagramTemplate[] = [
  {
    id: 'university',
    name: 'University Management',
    description: 'Person inheritance with Student, Professor, Course & Department associations',
    classes: [
      {
        id: 'cls-person',
        name: 'Person',
        stereotype: 'abstract',
        color: '#6366f1',
        attributes: [
          '# id: int',
          '# name: String',
          '# email: String',
          '# phone: String',
        ],
        methods: [
          '+ getId(): int',
          '+ getName(): String',
          '+ getEmail(): String',
          '+ getContactInfo(): String',
        ],
        x: 350,
        y: 40,
        width: 200,
      },
      {
        id: 'cls-student',
        name: 'Student',
        stereotype: 'class',
        color: '#3b82f6',
        attributes: [
          '- studentId: String',
          '- gpa: double',
          '- major: String',
        ],
        methods: [
          '+ getGpa(): double',
          '+ enroll(course: Course): boolean',
          '+ drop(course: Course): boolean',
          '+ calculateHonors(): boolean',
        ],
        x: 120,
        y: 280,
        width: 220,
      },
      {
        id: 'cls-professor',
        name: 'Professor',
        stereotype: 'class',
        color: '#10b981',
        attributes: [
          '- employeeId: String',
          '- department: String',
          '- salary: double',
        ],
        methods: [
          '+ assignGrade(student: Student, grade: String): void',
          '+ scheduleOfficeHours(time: String): void',
        ],
        x: 580,
        y: 280,
        width: 240,
      },
      {
        id: 'cls-course',
        name: 'Course',
        stereotype: 'class',
        color: '#f59e0b',
        attributes: [
          '- courseCode: String',
          '- title: String',
          '- credits: int',
          '- maxCapacity: int',
        ],
        methods: [
          '+ getCourseCode(): String',
          '+ getTitle(): String',
          '+ isFull(): boolean',
          '+ addStudent(student: Student): void',
        ],
        x: 350,
        y: 480,
        width: 220,
      },
    ],
    relationships: [
      {
        id: 'rel-1',
        sourceId: 'cls-student',
        targetId: 'cls-person',
        type: 'inheritance',
        label: 'extends',
      },
      {
        id: 'rel-2',
        sourceId: 'cls-professor',
        targetId: 'cls-person',
        type: 'inheritance',
        label: 'extends',
      },
      {
        id: 'rel-3',
        sourceId: 'cls-professor',
        targetId: 'cls-course',
        type: 'association',
        label: 'teaches',
        sourceMultiplicity: '1',
        targetMultiplicity: '1..*',
      },
      {
        id: 'rel-4',
        sourceId: 'cls-student',
        targetId: 'cls-course',
        type: 'association',
        label: 'enrolledIn',
        sourceMultiplicity: '*',
        targetMultiplicity: '1..*',
      },
    ],
  },
  {
    id: 'ecommerce',
    name: 'E-Commerce Order System',
    description: 'Customer, Order, OrderItem, Product & Payment with composition and interface',
    classes: [
      {
        id: 'cls-customer',
        name: 'Customer',
        stereotype: 'class',
        color: '#3b82f6',
        attributes: [
          '- customerId: int',
          '- name: String',
          '- email: String',
          '- shippingAddress: String',
        ],
        methods: [
          '+ placeOrder(): Order',
          '+ getOrderHistory(): List<Order>',
        ],
        x: 80,
        y: 60,
        width: 220,
      },
      {
        id: 'cls-order',
        name: 'Order',
        stereotype: 'class',
        color: '#8b5cf6',
        attributes: [
          '- orderId: int',
          '- orderDate: String',
          '- status: String',
          '- totalAmount: double',
        ],
        methods: [
          '+ calculateTotal(): double',
          '+ updateStatus(status: String): void',
          '+ cancelOrder(): boolean',
        ],
        x: 380,
        y: 60,
        width: 220,
      },
      {
        id: 'cls-orderitem',
        name: 'OrderItem',
        stereotype: 'class',
        color: '#ec4899',
        attributes: [
          '- quantity: int',
          '- unitPrice: double',
        ],
        methods: [
          '+ getSubtotal(): double',
        ],
        x: 380,
        y: 330,
        width: 190,
      },
      {
        id: 'cls-product',
        name: 'Product',
        stereotype: 'class',
        color: '#10b981',
        attributes: [
          '- productId: int',
          '- title: String',
          '- price: double',
          '- stockQuantity: int',
        ],
        methods: [
          '+ isAvailable(): boolean',
          '+ reduceStock(qty: int): void',
        ],
        x: 680,
        y: 330,
        width: 200,
      },
      {
        id: 'cls-payment',
        name: 'PaymentMethod',
        stereotype: 'interface',
        color: '#f59e0b',
        attributes: [],
        methods: [
          '+ processPayment(amount: double): boolean',
          '+ refund(amount: double): boolean',
        ],
        x: 680,
        y: 60,
        width: 220,
      },
    ],
    relationships: [
      {
        id: 'rel-e1',
        sourceId: 'cls-customer',
        targetId: 'cls-order',
        type: 'association',
        label: 'places',
        sourceMultiplicity: '1',
        targetMultiplicity: '*',
      },
      {
        id: 'rel-e2',
        sourceId: 'cls-order',
        targetId: 'cls-orderitem',
        type: 'composition',
        label: 'contains',
        sourceMultiplicity: '1',
        targetMultiplicity: '1..*',
      },
      {
        id: 'rel-e3',
        sourceId: 'cls-orderitem',
        targetId: 'cls-product',
        type: 'association',
        label: 'references',
        sourceMultiplicity: '*',
        targetMultiplicity: '1',
      },
      {
        id: 'rel-e4',
        sourceId: 'cls-order',
        targetId: 'cls-payment',
        type: 'association',
        label: 'paidVia',
        sourceMultiplicity: '1',
        targetMultiplicity: '1',
      },
    ],
  },
  {
    id: 'hospital',
    name: 'Hospital Management',
    description: 'Patient, Doctor, Appointment, and MedicalRecord architecture',
    classes: [
      {
        id: 'cls-patient',
        name: 'Patient',
        stereotype: 'class',
        color: '#3b82f6',
        attributes: [
          '- patientId: String',
          '- name: String',
          '- age: int',
          '- bloodGroup: String',
        ],
        methods: [
          '+ requestAppointment(doctor: Doctor): Appointment',
          '+ getMedicalHistory(): String',
        ],
        x: 100,
        y: 100,
        width: 230,
      },
      {
        id: 'cls-doctor',
        name: 'Doctor',
        stereotype: 'class',
        color: '#10b981',
        attributes: [
          '- doctorId: String',
          '- name: String',
          '- specialty: String',
          '- consultationFee: double',
        ],
        methods: [
          '+ diagnose(patient: Patient): void',
          '+ prescribeMedication(drug: String): void',
        ],
        x: 550,
        y: 100,
        width: 230,
      },
      {
        id: 'cls-appointment',
        name: 'Appointment',
        stereotype: 'class',
        color: '#f59e0b',
        attributes: [
          '- appointmentId: int',
          '- dateTime: String',
          '- status: String',
        ],
        methods: [
          '+ reschedule(newTime: String): boolean',
          '+ cancel(): void',
        ],
        x: 320,
        y: 350,
        width: 220,
      },
    ],
    relationships: [
      {
        id: 'rel-h1',
        sourceId: 'cls-patient',
        targetId: 'cls-appointment',
        type: 'association',
        label: 'schedules',
        sourceMultiplicity: '1',
        targetMultiplicity: '*',
      },
      {
        id: 'rel-h2',
        sourceId: 'cls-doctor',
        targetId: 'cls-appointment',
        type: 'association',
        label: 'conducts',
        sourceMultiplicity: '1',
        targetMultiplicity: '*',
      },
    ],
  },
];
