import {
  parseAttribute,
  parseMethod,
  generateClassJavaCode,
  generateAllJavaCode,
  generatePlantUML,
  generateMermaid,
} from './utils/codeGenerator';
import { TEMPLATES } from './utils/diagramTemplates';
import { UMLClass, UMLRelationship, DiagramData } from './types/uml';

describe('UML Code Generator & Utilities', () => {
  test('parses attributes with UML visibility symbols correctly', () => {
    const attr1 = parseAttribute('+ name: String');
    expect(attr1).toEqual({
      visibility: 'public',
      name: 'name',
      type: 'String',
      defaultValue: undefined,
    });

    const attr2 = parseAttribute('- age: int = 18');
    expect(attr2).toEqual({
      visibility: 'private',
      name: 'age',
      type: 'int',
      defaultValue: '18',
    });

    const attr3 = parseAttribute('# salary: double');
    expect(attr3).toEqual({
      visibility: 'protected',
      name: 'salary',
      type: 'double',
      defaultValue: undefined,
    });

    const attr4 = parseAttribute('~ department: String');
    expect(attr4).toEqual({
      visibility: '',
      name: 'department',
      type: 'String',
      defaultValue: undefined,
    });
  });

  test('parses methods with parameters and return types correctly', () => {
    const m1 = parseMethod('+ getName(): String');
    expect(m1).toEqual({
      visibility: 'public',
      name: 'getName',
      returnType: 'String',
      parameters: [],
    });

    const m2 = parseMethod('+ setAge(age: int): void');
    expect(m2).toEqual({
      visibility: 'public',
      name: 'setAge',
      returnType: 'void',
      parameters: [{ name: 'age', type: 'int' }],
    });

    // Handle parameter type only (auto naming)
    const m3 = parseMethod('setAge(int): void');
    expect(m3?.parameters[0].type).toBe('int');
    expect(m3?.parameters[0].name).toBeTruthy();
  });

  test('generates complete Java code with inheritance and association', () => {
    const person: UMLClass = {
      id: 'c1',
      name: 'Person',
      stereotype: 'abstract',
      attributes: ['# id: int', '# name: String'],
      methods: ['+ getId(): int', '+ getName(): String'],
      x: 100,
      y: 100,
    };

    const student: UMLClass = {
      id: 'c2',
      name: 'Student',
      stereotype: 'class',
      attributes: ['- gpa: double'],
      methods: ['+ getGpa(): double'],
      x: 100,
      y: 300,
    };

    const course: UMLClass = {
      id: 'c3',
      name: 'Course',
      stereotype: 'class',
      attributes: ['- code: String'],
      methods: ['+ getCode(): String'],
      x: 400,
      y: 300,
    };

    const rels: UMLRelationship[] = [
      {
        id: 'r1',
        sourceId: 'c2',
        targetId: 'c1',
        type: 'inheritance',
        label: 'extends',
      },
      {
        id: 'r2',
        sourceId: 'c2',
        targetId: 'c3',
        type: 'association',
        targetMultiplicity: '*',
      },
    ];

    const studentCode = generateClassJavaCode(student, [person, student, course], rels);
    expect(studentCode).toContain('public class Student extends Person {');
    expect(studentCode).toContain('private List<Course>');
    expect(studentCode).toContain('public double getGpa()');
    expect(studentCode).toContain('return 0.0;');
    expect(studentCode).toContain('public Student(');
    expect(studentCode).toContain('public void setGpa(');
    expect(studentCode).toContain('public String toString()');
  });

  test('generates all Java code files and combined file map', () => {
    const university = TEMPLATES[0];
    const { files, combined } = generateAllJavaCode(university.classes, university.relationships);
    expect(Object.keys(files).length).toBe(university.classes.length);
    expect(files['Person.java']).toContain('public abstract class Person');
    expect(files['Student.java']).toContain('public class Student extends Person');
    expect(combined).toContain('// Generated by UML Class Diagram Generator');
  });

  test('generates PlantUML and Mermaid diagrams', () => {
    const university = TEMPLATES[0];
    const puml = generatePlantUML(university.classes, university.relationships);
    expect(puml).toContain('@startuml');
    expect(puml).toContain('@enduml');
    expect(puml).toContain('class Person <<abstract>>');
    expect(puml).toContain('Student --|> Person');

    const mmd = generateMermaid(university.classes, university.relationships);
    expect(mmd).toContain('classDiagram');
    expect(mmd).toContain('Person <|-- Student');
  });

  test('validates diagram JSON export and import schema', () => {
    const sampleDiagram: DiagramData = {
      title: 'Test Diagram',
      version: '2.0',
      timestamp: new Date().toISOString(),
      classes: TEMPLATES[0].classes,
      relationships: TEMPLATES[0].relationships,
    };

    const json = JSON.stringify(sampleDiagram);
    const parsed = JSON.parse(json);

    expect(parsed.title).toBe('Test Diagram');
    expect(Array.isArray(parsed.classes)).toBe(true);
    expect(Array.isArray(parsed.relationships)).toBe(true);
    expect(parsed.classes.length).toBe(TEMPLATES[0].classes.length);
  });

  test('all templates have valid structure and connected IDs', () => {
    expect(TEMPLATES.length).toBeGreaterThanOrEqual(3);
    for (const tmpl of TEMPLATES) {
      const classIds = new Set(tmpl.classes.map((c) => c.id));
      for (const rel of tmpl.relationships) {
        expect(classIds.has(rel.sourceId)).toBe(true);
        expect(classIds.has(rel.targetId)).toBe(true);
      }
    }
  });
});
